"""users dt and coordinates info

Revision ID: 7b9fe89befbf
Revises: 
Create Date: 2020-03-29 18:53:24.217551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9fe89befbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dt_coor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_start', sa.DateTime(), nullable=False),
    sa.Column('dt_finish', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dt_coor')
    # ### end Alembic commands ###
